#!/usr/bin/env node
// T17: assemble the report's figures into one compilable LaTeX document.
//
// `docs-notes/FIGURES.md` holds every figure three times over (prose, Mermaid,
// TikZ) together with a keep/cut recommendation. This script takes the TikZ of
// the figures the summary table keeps, in the numbering that table assigns, and
// writes `report-figures.tex`: one figure per page, for approval and for
// finding compile errors before the chapter does.
//
//   node docs-notes/figures/build-figures.mjs
//
// The source of truth stays FIGURES.md. Edit a figure there, then re-run this.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(here, "..", "FIGURES.md");
const TARGET = join(here, "report-figures.tex");

// The summary table's decision, and the figure numbers it assigns.
const CHAPTER3 = ["F1", "F2", "F3", "F5", "F6", "F8", "F11", "F19", "F21", "F22", "F23", "F24"];
const CHAPTER4 = ["F14", "F17"];

const FENCE = "`".repeat(3);

function parse(markdown) {
  const lines = markdown.split("\n");
  const heads = [];
  lines.forEach((line, index) => {
    const match = /^## (F\d+): (.*)$/.exec(line);
    if (match) {
      heads.push({ index, id: match[1], title: match[2] });
    }
  });
  heads.push({ index: lines.length, id: null, title: null });

  const figures = new Map();
  for (let i = 0; i < heads.length - 1; i += 1) {
    const { index, id, title } = heads[i];
    const segment = lines.slice(index, heads[i + 1].index);
    const tikz = segment.findIndex((line) => line.trim() === "### TikZ form");
    if (tikz === -1) {
      continue;
    }
    const open = segment.findIndex((line, j) => j > tikz && line.trim() === `${FENCE}latex`);
    if (open === -1) {
      continue;
    }
    const close = segment.findIndex((line, j) => j > open && line.trim() === FENCE);
    if (close === -1) {
      continue;
    }
    figures.set(id, { title, body: segment.slice(open + 1, close).join("\n") });
  }

  // The first two latex fences in the file are the shared preamble and the
  // style block every figure below depends on.
  const preamble = [];
  for (let i = 0; i < lines.length && preamble.length < 2; i += 1) {
    if (lines[i].trim() !== `${FENCE}latex`) {
      continue;
    }
    const close = lines.findIndex((line, j) => j > i && line.trim() === FENCE);
    preamble.push(lines.slice(i + 1, close).join("\n"));
  }
  return { figures, preamble };
}

// The PSUT template is a T1/lmodern document. Keep the text this script itself
// controls to ASCII, so a missing glyph never fails a build.
function escapeTitle(title) {
  return (
    title
      .replaceAll("&", "\\&")
      .replaceAll("_", "\\_")
      .replaceAll("\u2026", "\\dots ")
      .replaceAll("\u00b7", "\\textperiodcentered ")
      .replaceAll("\u201c", "``")
      .replaceAll("\u201d", "''")
      // A straight " is a closing quote to LaTeX, so a quoted phrase opened with one
      // came out with both quotes facing the same way.
      .replace(/"([^"]*)"/g, "``$1''")
  );
}

function build({ figures, preamble }) {
  const numbers = new Map(CHAPTER3.map((id, i) => [id, `3.${i + 1}`]));
  numbers.set("F14", "4.1");
  numbers.set("F17", "4.2");

  const out = [
    "% Generated by docs-notes/figures/build-figures.mjs. Do not edit by hand:",
    "% edit the TikZ in docs-notes/FIGURES.md and re-run the script.",
    "\\documentclass[11pt,a4paper]{article}",
    "\\usepackage[T1]{fontenc}",
    "\\usepackage[utf8]{inputenc}",
    "\\usepackage{lmodern}",
    "\\usepackage{booktabs}",
    "\\usepackage{textcomp}",
    // \resizebox, which three of the figures use to fit the text block.
    "\\usepackage{graphicx}",
    "\\usepackage[margin=20mm]{geometry}",
    preamble[0],
    preamble[1],
    "\\begin{document}",
    "\\begin{center}\\Large\\textbf{Governance layer: report figures}\\\\[2pt]",
    "\\normalsize Extracted from \\texttt{docs-notes/FIGURES.md} for T17 approval.\\end{center}",
    "\\vspace{4mm}",
  ];

  const missing = [];
  for (const [group, label] of [
    [CHAPTER3, "Chapter 3"],
    [CHAPTER4, "Chapter 4"],
  ]) {
    out.push(`\\section*{${label}}`);
    for (const id of group) {
      const figure = figures.get(id);
      if (!figure) {
        missing.push(id);
        continue;
      }
      out.push(
        `\\subsection*{Figure ${numbers.get(id)} \\textnormal{(${id}: ${escapeTitle(figure.title)})}}`,
        "\\begin{center}",
        figure.body,
        "\\end{center}",
        "\\clearpage",
      );
    }
  }
  out.push("\\end{document}");
  return { text: `${out.join("\n")}\n`, missing };
}

const parsed = parse(readFileSync(SOURCE, "utf8"));
const { text, missing } = build(parsed);
writeFileSync(TARGET, text, "utf8");
const kept = CHAPTER3.length + CHAPTER4.length - missing.length;
console.log(`report-figures.tex: ${kept} figures (${text.length} bytes)`);
if (missing.length > 0) {
  console.error(`No TikZ form found for: ${missing.join(", ")}`);
  process.exitCode = 1;
}
